;;;; Forms containing FFI.

(module Main)

;;; 8.4 Foreign Declarations

(foreign import ccall "sin"
  (:: csin (-> Double Double)))

(foreign import ccall (safe "cos")
  (:: ccos (-> Double Double)))

(foreign import ccall (unsafe "math.h tan")
  (:: ctan (-> Double Double)))

(:: s8_4 (IO ()))
(= s8_4
  (do (print (csin (* pi 0.5)))
      (print (ccos (* pi 2)))
      (print (ctan pi))))

;;; Main

(:: main (IO ()))
(= main
  s8_4)
