;;; -*- mode: sk -*-

(module Main)

;;; 12.1 Inlining

(:: inlineMe Int)
(= inlineMe 42)
##(INLINE inlineMe)

(:: dontInlineMe Int)
(= dontInlineMe 43)
##(NOINLINE dontInlineMe)

(:: iAmInlinable Int)
(= iAmInlinable 44)
##(INLINABLE iAmInlinable)

(:: inlineprgm (IO ()))
(= inlineprgm
  (do (print inlineMe)
      (print dontInlineMe)
      (print iAmInlinable)))

;;; 12.2 Specialization

;;; TODO

;;; 12.3 Language extensions

;;; TODO

;;; GHC extension: UNPACK

(data D1
  (C1 ##UNPACK (! Int) ##UNPACK (! Char))
  (deriving (Eq Show)))

(:: unpackprgm (IO ()))
(= unpackprgm
  (print (C1 42 \x)))

(:: main (IO ()))
(= main
  (do inlineprgm
      unpackprgm))
