;;;; Forms containing type declarations.

(module Main)

;;; 4.2 User-Defined Datatypes

;;; 4.1.1 Algebraic Datatype Declarations

(data MyData1
  (MyConst1 Int Bool)
  (MyConst2 [(, Int Int)] Double Char)
  (deriving (Eq Show)))

(:: s4_1_1 (IO ()))
(= s4_1_1
  (do (print (MyConst1 123 True))
      (print (MyConst2 [(, 1 2) (, 3 4)] 1.23 \z))))

(:: s4_1 (IO ()))
(= s4_1
  s4_1_1)

;;; 4.4 Nested Declarations

;; Unit type.
(:: foo ())
(= foo
  ())

;;; Simple function type.
(:: bar (-> String (IO ())))
(= (bar str)
  (putStrLn (++ "From bar: " str)))

;;; Another function type, taking multiple arguments.
(:: buzz (-> Int (-> Bool (-> String (IO ())))))
(= (buzz i b s)
  (do (putStrLn (++ "Int: " (show i)))
      (putStrLn (++ "Bool: " (show b)))
      (putStrLn (++ "String: " (show s)))))

;;; Function taking higher order function.
(:: quux (-> (-> Int Int) Int))
(= (quux f)
  (f 6))

;;; Function taking list.
(:: listy (-> [Int] (IO ())))
(= (listy xs)
  (mapM_ print xs))

;;; Function with type variables.
(:: tv01 (-> a (-> [b] Int)))
(= (tv01 x ys)
  (length ys))

;;; Main.
(:: main (IO ()))
(= main
  (do s4_1
      (print foo)
      (bar "BAR")
      (buzz 1 True "buzz")
      (print (quux (\ (n) (* (+ n 1) n))))
      (listy [1 2 3])
      (print (tv01 True [1 2 3]))))
