;;; File containing forms using macros.

(module Main)

(import SK.Core)

;;; Simple `defmacro'
(defmacro m1 (x)
  (return `(putStrLn (++ "Hello, " ,x))))

;; Simple `macrolet'.
(macrolet ((m2 (a b c)
             (return `(,a (+ ,b ,c)))))
  (:: f1 (-> Int (-> Int (IO ()))))
  (= (f1 x y)
    (m2 print x y)))

;;; Macro taking fractional value as argument.
(macrolet ((m1 (n)
             (case (fromForm n)
               ((Just d) (if (<= 1.0 (:: d Double))
                             (return '"more or eq")
                             (return '"less")))
               (Nothing (failS "m1: error")))))
  (= fracmac
    (do (putStrLn (m1 1.1))
        (putStrLn (m1 0.9)))))

;;; Macro returning haskell list.
(macrolet ((m2 (a b c)
             (let ((= f
                     (case (do (<- x (fromForm a))
                               (<- y (fromForm b))
                               (<- z (fromForm c))
                               (return (:: (, x y z)
                                           (, Int Int Int))))
                       ((Just (, x y z))
                        (return `[,(toForm (* x 100))
                                  ,(toForm (* y 100))
                                  ,(toForm (* z 100))]))
                       (_ (failS "error: m2")))))
               f)))
  (:: hslistmac (IO ()))
  (= hslistmac
    (print (m2 1 2 3))))

(:: main (IO ()))
(= main
  (do (m1 "macro")
      (f1 11 31)
      fracmac
      hslistmac))
