branches:
  only:
    - /appveyor-*/

environment:
  global:
    CABOPTS: "--store-dir=C:\\SR --http-transport=plain-http"
    GHCVER: 8.10.2
    CABALVER: 3.2.0.0

clone_folder: "C:\\WORK"
clone_depth: 5

cache:
  - C:\SR

install:
  - choco install -y cabal --version %CABALVER%
  - choco install -y ghc --version %GHCVER%
  - refreshenv

before_build:
  - cabal --version
  - ghc --version
  - cabal %CABOPTS% v2-update

build_script:
  - cabal %CABOPTS% v2-configure --disable-optimization --disable-library-profiling
  - cabal %CABOPTS% v2-build all -j --only-dependencies
  - cabal %CABOPTS% v2-build all
  - cabal %CABOPTS% v2-test all
