language: c

git:
  depth: 3

cache:
  directories:
    - $HOME/.stack
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.ghcup
    - $HOME/AppData/Local/Programs/stack
    - $HOME/AppData/Roaming/stack

addons:
  apt:
    packages:
      - libgmp-dev
  homebrew:
    # Workaround for "Unknown command: bundle", see: https://bit.ly/32d3V2d
    update: true

jobs:
  include:
    - os: linux
      env: EXEC=stack RESOLVER=lts-11
    - os: linux
      env: EXEC=stack RESOLVER=lts-12
    - os: linux
      env: EXEC=stack RESOLVER=lts-14
    - os: linux
      env: EXEC=stack RESOLVER=lts-15
    - os: linux
      env: EXEC=cabal GHC_VERSION=8.8.3
    - os: linux
      env: EXEC=cabal GHC_VERSION=8.10.1
    - os: osx
      env: EXEC=stack RESOLVER=lts-15
    - os: windows
      env: EXEC=stack RESOLVER=lts-14
  allow_failures:
    - os: windows
      env: EXEC=stack RESOLVER=lts-15

before_install:
  - . scripts/travis.sh

install:
  - travis_install

script:
  - travis_script

after_success:
  - travis_after_success

notification:
  email: false
