# Use the latest 2.1 version of CircleCI pipeline process engine. See:
# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-linux:
    docker:
      - image: fpco/stack-build:lts-15.4
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - stack-{{ checksum "stack.yaml" }}
            - kernel-{{ checksum "kernel/finkel-kernel.cabal" }}
            - kernel-{{ checksum "fkc/fkc.cabal" }}
            - setup-{{ checksum "setup/finkel-setup.cabal" }}
            - lang-{{ checksum "lang/finkel-lang.cabal" }}
            - tool-{{ checksum "tool/finkel-tool.cabal" }}
            - finkel-{{ checksum "finkel/finkel.cabal" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Build Packages
          command: stack --no-terminal build --test --no-run-tests
      - run:
          name: Run tests
          command: RESOLVER=lts-15.4 stack --no-terminal build --test
      - save_cache:
          name: Cache dependencies
          key: stack-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ~/.stack-work

workflows:
  build:
    jobs:
      - build-linux:
          filters:
            branches:
              only:
                - /circleci-.*/
