# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'sk'
copyright = '2019-2020, 8c6794b6'
author = '8c6794b6'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = None
# pygments_style = 'colorful'
# pygments_style = 'default'
# pygments_style = 'emacs'
pygments_style = 'friendly'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
# html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {}

# For 'alabaster' theme
# html_theme_options = {
#     'fixed_sidebar': True,
#     'show_relbars': True,
# }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Skdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Sk.tex', 'Sk Documentation',
     '8c6794b6', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'sk', 'Sk Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Sk', 'Sk Documentation',
     author, 'Sk', 'Lisp Flavored Haskell',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Custom setup function

from pygments.lexer import RegexLexer
from pygments import token
from sphinx.highlighting import lexers

import re

class SkLexer(RegexLexer):
    name = 'sk'
    reserved = (
        # haskell 2010
        'case', 'class', 'data', 'default', 'deriving', 'do',
        'family', 'if', 'infix[lr]?', 'instance', 'let', 'newtype',
        'type', 'where',
        '_', '=', '=>', '<-', '->', '::',

        # sk kernel special forms
        ':begin', ':eval-when-compile', ':quote', ':quasiquote',
        ':require', ':unquote', ':unquote-splice',

        # sk core
        'eval-when', 'export', 'defn', 'defmacro', 'defmodule',
        'macrolet', 'require'
    )
    tokens = {
        'root': [
            # Whitespace:
            # (r'(\n\s*|\t)', token.Whitespace),
            (r'\s+', token.Text),

            # Comment:
            (r'#\;', token.Comment.Multiline, 'multiline-comment'),
            (r';.*', token.Comment.Single),

            # Lexemes:
            (r'\bimport\b', token.Keyword.Reserved),
            (r'\bmodule\b', token.Keyword.Reserved),

            # Numbers
            (r'-?\d+\.\d+', token.Number.Float),
            (r'-?\d+', token.Number.Integer),

            # Characters
            (r"#'( |[^ ]+)", token.String.Char),

            ('(%s)' % '|'.join(re.escape(e) + ' ' for e in reserved),
             token.Keyword.Reserved),

            # Types
            (r'([A-Z][0-9a-zA-Z\-_]*)', token.Keyword.Type),

            # Operators
            (r'([!@$%^&*-=+?/<>\|~]+)', token.Operator),
            (r'(,@|,)', token.Operator),

            # Variable identifier
            (r'[_a-z][\w\']*', token.Name),

            (r'"[^"]*"', token.String),

            # Reserved:
            # (r'(%s)' % '|'.join(reserved),
            #  token.Keyword.Reserved),

            # ('(%s)' % '|'.join(re.escape(r) + ' ' for r in reserved),
            #  token.Keyword),

            (r'\\', token.Keyword.Reserved),

            # Pragma:
            (r'#p\(.*', token.Comment),

            (r'(\(|\))', token.Punctuation),
            (r'(\[|\])', token.Punctuation),
            (r'(\{|\})', token.Punctuation),
            (r'`', token.Punctuation),
            (r"'", token.Punctuation)
        ],
        'multiline-comment': [
            (r'#\;', token.Comment.Multiline, '#push'),
            (r'\;#', token.Comment.Multiline, '#pop'),
            (r'[^;#]+', token.Comment.Multiline),
            (r'[;#]', token.Comment.Multiline),
        ]
    }

def setup(sphinx):
    sphinx.add_lexer("sk", SkLexer())
