;;; Setup script for SK package.

(:docn "Module exporting functions for Cabal setup script.")

(:require SK.Core)

(defmodule SK.Setup
  (export
   skMakeMain
   defaultMainWithHooks
   skcHooksWith)
  (use
   ;; sk-kernel
   (Distribution.Simple.SK)))

(defn (:: skMakeMain (IO ()))
  "Main function with @make@ command.

Intended to be used from cabal setup script."
  (skcMainWith "sk" ["make"]))
