# File: my-first-package/package.yaml

name: my-first-package
version: 0.1.0.0

library:
  source-dirs: src
  exposed-modules: MyFirstPackage
  ghc-options:
    - -F -pgmF fnkpp -optF --no-warn-interp
    - -fplugin Finkel.Core.Plugin
  build-tools:
    - fnkpp:fnkpp
  dependencies:
    - base
    - finkel-core
