name: build

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

jobs:
  stack:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        plan:
          - resolver: "lts-11"
          - resolver: "lts-12"
          - resolver: "lts-14"
          - resolver: "lts-16"
        exclude:
          - os: macos-latest
            plan:
              resolver: "lts-11"
          - os: macos-latest
            plan:
              resolver: "lts-12"
          - os: macos-latest
            plan:
              resolver: "lts-14"
          - os: windows-latest
            plan:
              resolver: "lts-11"
          - os: windows-latest
            plan:
              resolver: "lts-12"
          - os: windows-latest
            plan:
              resolver: "lts-16"

    env:
      STACK: stack --resolver=${{ matrix.plan.resolver }}
      RESOLVER: ${{ matrix.plan.resolver }}

    runs-on:
      - ${{ matrix.os }}

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Cache stack package database (non-windows)
        id: cache-stack-pkg-db-non-win
        if: matrix.os != 'windows-latest'
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-pkg-db-${{ matrix.plan.resolver }}-${{ hashFiles('stack.yaml') }}

      - name: Cache stack packages database (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Roaming\stack
          key: ${{ runner.os }}-stack-pkg-db-${{ matrix.plan.resolver }}-${{ hashFiles('stack.yaml') }}

      - name: Cache stack (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Programs\stack
          key: ${{ runner.os }}-stack-local-${{ matrix.plan.resolver }}

      - name: Show stack version
        shell: bash
        run: $STACK --version

      - name: Add PATH for executable installed with stack (linux)
        if: matrix.os == 'ubuntu-latest'
        run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Add PATH for executable installed with stack (osx)
        if: matrix.os == 'macos-latest'
        run: echo "/Users/runner/.local/bin" >> $GITHUB_PATH

      - name: Add PATH for executable installed with stack (windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: echo "C:/Users/runneradmin/AppData/Roaming/local/bin" >> $GITHUB_PATH

      - name: Setup stack
        shell: bash
        run: $STACK setup

      - name: Install dependency packages
        shell: bash
        run: $STACK build -j 2 --test --only-dependencies

      - name: Build packages
        shell: bash
        run: $STACK build --fast --test --coverage --no-run-tests

      - name: Run tests
        shell: bash
        run: RESOLVER=${{ matrix.plan.resolver }} $STACK --jobs 1 build --fast --test --coverage

      - name: Generate coverge report
        shell: bash
        run: |
          $STACK install hpc-codecov
          HPCROOT=$($STACK path --local-hpc-root)
          DISTDIR=$($STACK path --dist-dir)
          DOCPKG=doc/include/building-package
          TIX=$(find $HPCROOT -name 'all.tix')
          hpc-codecov \
            --src=kernel --mix=kernel/$DISTDIR/hpc \
            --src=setup --mix=setup/$DISTDIR/hpc \
            --src=core --mix=core/$DISTDIR/hpc \
            --src=tool --mix=tool/$DISTDIR/hpc \
            --src=$DOCPKG/my-second-package \
            --mix=$DOCPKG/my-second-package/$DISTDIR/hpc \
            --src=$DOCPKG/my-new-package \
            --mix=$DOCPKG/my-new-package/$DISTDIR/hpc \
            --out=codecov.json --verbose $TIX

      - name: Send coverage report
        shell: bash
        run: bash <(curl -s https://codecov.io/bash)

  cabal:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        plan:
          - ghc: "8.10.2"
            cabal: "3.2.0.0"
            flags: "-O0"
          - ghc: "8.10.2"
            cabal: "3.2.0.0"
            flags: "-O2"
        exclude:
          - os: windows-latest
            plan:
              ghc: "8.10.2"
              cabal: "3.2.0.0"
              flags: "-O0"
          - os: windows-latest
            plan:
              ghc: "8.10.2"
              cabal: "3.2.0.0"
              flags: "-O2"
    runs-on:
      - ${{ matrix.os }}

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v2

      - name: Cache ~/.ghcup
        id: home-dot-ghcup
        uses: actions/cache@v2
        with:
          path: ~/.ghcup
          key: ${{ runner.os }}-ghcup-${{ matrix.plan.ghc }}

      - name: Cache cabal package database
        id: home-dot-cabal
        uses: actions/cache@v2
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-cabal-pkg-db-${{ matrix.plan.ghc }}-${{ hashFiles('cabal.project') }}

      # Manually installing ghc and bundled packages with "ghcup" for Linux and
      # OSX, because the setup-haskell action may reuse the preinstalled GHC in
      # the github runner, and the preinstalled GHC does not contain profiling
      # library for the "base" package. Without profiling libraries, "doc"
      # package tests will fail.

      - name: Install ghcup (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          url='https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup'
          mkdir -p ~/.ghcup/bin
          curl -sL $url > ~/.ghcup/bin/ghcup
          chmod +x ~/.ghcup/bin/ghcup
          echo "$HOME/.ghcup/bin" >> $GITHUB_PATH

      - name: Install ghcup (osx)
        if: matrix.os == 'macos-latest'
        run: |
          url='https://downloads.haskell.org/~ghcup/x86_64-apple-darwin-ghcup'
          mkdir -p ~/.ghcup/bin
          curl -sL $url > ~/.ghcup/bin/ghcup
          chmod +x ~/.ghcup/bin/ghcup
          echo "$HOME/.ghcup/bin" >> $GITHUB_PATH

      - name: Install ghc and cabal-install (linux and osx)
        if: matrix.os != 'windows-latest'
        run: |
          ghcup install cabal ${{ matrix.plan.cabal }}
          ghcup install ghc ${{ matrix.plan.ghc }}
          ghcup set ghc ${{ matrix.plan.ghc }}
          which cabal
          which ghc
          cabal --version
          ghc --version

      - name: Install ghc and cabal-install (windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
          choco install -y cabal --version ${{ matrix.plan.cabal }}
          choco install -y ghc --version ${{ matrix.plan.ghc }}
          refreshenv
          echo "C:/Users/runneradmin/AppData/Roaming/cabal/bin" >> $GITHUB_PATH
          echo "C:/ProgramData/chocolatey/lib/ghc/tools/ghc-${{matrix.plan.ghc }}/bin" >> $GITHUB_PATH

      - name: Show version and paths
        shell: bash
        run: |
          ghc --version
          cabal --version

      - name: Update cabal package list
        shell: bash
        run: cabal v2-update

      - name: Write cabal.project.local with v2-configure (non-windows)
        shell: bash
        if: matrix.os != 'windows-latest'
        run: cabal v2-configure ${{ matrix.plan.flags }}

      - name: Write cabal.project.local with v2-configure (windows)
        shell: bash
        if: matrix.os == 'windows-latest'
        run: cabal v2-configure --disable-library-profiling ${{ matrix.plan.flags }}

      - name: Build dependency packages
        shell: bash
        run: cabal v2-build all -j --only-dependencies

      - name: Build packages
        shell: bash
        run: cabal v2-build all

      - name: Run tests
        shell: bash
        run: cabal v2-test all

      - name: Run haddock
        shell: bash
        run: cabal v2-haddock all
