name: build

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

jobs:
  stack:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        plan:
          - resolver: "lts-11"
          - resolver: "lts-12"
          - resolver: "lts-14"
          - resolver: "lts-15"
        exclude:
          - os: macos-latest
            plan:
              resolver: "lts-11"
          - os: macos-latest
            plan:
              resolver: "lts-12"
          - os: macos-latest
            plan:
              resolver: "lts-14"
          - os: windows-latest
            plan:
              resolver: "lts-11"
          - os: windows-latest
            plan:
              resolver: "lts-12"
          - os: windows-latest
            plan:
              resolver: "lts-15"

    env:
      STACK: stack --resolver=${{ matrix.plan.resolver }}
      RESOLVER: ${{ matrix.plan.resolver }}

    runs-on:
      - ${{ matrix.os }}

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Cache stack package database (non-windows)
        id: cache-stack-pkg-db-win
        if: matrix.os != 'windows-latest'
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-pkg-db-${{ matrix.plan.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-pkg-db

      - name: Cache stack (windows)
        id: cache-stack-win
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v1
        with:
          path: C:\Users\runneradmin\AppData\Local\Programs\stack
          key: ${{ runner.os }}-stack-local-${{ matrix.plan.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-local-${{ matrix.plan.resolver }}

      - name: Cache stack packages (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v1
        with:
          path: C:\Users\runneradmin\AppData\Roaming\stack
          key: ${{ runner.os }}-stack-pkg-db-${{ matrix.plan.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-pkg-db-${{ matrix.plan.resolver }}

      - name: Install stack (non-windows)
        if: matrix.os != 'windows-latest'
        uses: mstksg/setup-stack@v1

      # setup-stack@v1 action does not support windows, installing manually.
      # See: https://github.com/mstksg/setup-stack/issues/5
      - name: Install stack (windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          url=https://get.haskellstack.org/stable/windows-x86_64.zip
          curl --silent --output stack.zip --location $url
          7z x stack.zip stack.exe
          mkdir -p C:/Users/runneradmin/AppData/Roaming/local/bin
          mv stack.exe C:/Users/runneradmin/AppData/Roaming/local/bin
          echo "::add-path::C:/Users/runneradmin/AppData/Roaming/local/bin"

      - name: Show stack version
        shell: bash
        run: $STACK --version

      - name: Setup stack
        shell: bash
        run: $STACK setup

      - name: Install dependency packages
        shell: bash
        run: $STACK build -j 2 --test --only-dependencies

      - name: Build packages
        shell: bash
        run: $STACK build --fast --test --coverage --no-run-tests

      - name: Show resolver
        shell: bash
        run: echo $RESOLVER

      - name: Run tests
        shell: bash
        run: RESOLVER=${{ matrix.plan.resolver }} $STACK --jobs 1 build --fast --test --coverage

      - name: Generate coverge report
        shell: bash
        run: |
          $STACK install hpc-codecov
          HPCROOT=$($STACK path --local-hpc-root)
          DISTDIR=$($STACK path --dist-dir)
          DOCPKG=doc/include/building-package
          TIX=$(find $HPCROOT -name 'all.tix')
          hpc-codecov \
            --src=kernel --mix=kernel/$DISTDIR/hpc \
            --src=setup --mix=setup/$DISTDIR/hpc \
            --src=lang --mix=lang/$DISTDIR/hpc \
            --src=tool --mix=tool/$DISTDIR/hpc \
            --src=$DOCPKG/my-second-package \
            --mix=$DOCPKG/my-second-package/$DISTDIR/hpc \
            --src=$DOCPKG/my-new-package \
            --mix=$DOCPKG/my-new-package/$DISTDIR/hpc \
            --out=codecov.json --verbose $TIX

      - name: Send coverage report
        shell: bash
        run: bash <(curl -s https://codecov.io/bash)

  cabal:
    strategy:
      matrix:
        os:
          # setup-haskell@v1 action does not support windows and macos.
          # See: https://github.com/actions/setup-haskell/issues/1
          - ubuntu-latest
          - windows-latest
        plan:
          - ghc: "8.8.3"
            cabal: "3.0.0.0"
          - ghc: "8.10.1"
            cabal: "3.2.0.0"
        exclude:
          - os: windows-latest
            plan:
              ghc: "8.8.3"
              cabal: "3.0.0.0"
          - os: windows-latest
            plan:
              ghc: "8.10.1"
              cabal: "3.2.0.0"

    runs-on:
      - ${{ matrix.os }}

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v2

      - name: Cache ~/.ghcup
        id: home-dot-ghcup
        uses: actions/cache@v1
        with:
          path: ~/.ghcup
          key: ${{ runner.os }}-ghcup-${{ matrix.plan.ghc }}

      - name: Cache cabal package database
        id: home-dot-cabal
        uses: actions/cache@v1
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-cabal-pkg-db-${{ matrix.plan.ghc }}-${{ hashFiles('cabal.project') }}

      - name: Install ghcup (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          url='https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup'
          mkdir -p ~/.ghcup/bin
          curl -sL $url > ~/.ghcup/bin/ghcup
          chmod +x ~/.ghcup/bin/ghcup
          echo "::add-path::$HOME/.ghcup/bin"

      - name: Install ghcup (osx)
        if: matrix.os == 'macos-latest'
        run: |
          url='https://downloads.haskell.org/~ghcup/x86_64-apple-darwin-ghcup'
          mkdir -p ~/.ghcup/bin
          curl -sL $url > ~/.ghcup/bin/ghcup
          chmod +x ~/.ghcup/bin/ghcup
          echo "::add-path::$HOME/.ghcup/bin"

      - name: Install ghc and cabal-install (linux and osx)
        if: matrix.os != 'windows-latest'
        run: |
          ghcup -c install-cabal ${{ matrix.plan.cabal }}
          ghcup -c install ${{ matrix.plan.ghc }}
          ghcup set ${{ matrix.plan.ghc }}
          which cabal
          which ghc
          cabal --version
          ghc --version

      - name: Install ghc and cabal-install (windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
          choco install -y cabal --version ${{ matrix.plan.cabal }}
          choco install -y ghc --version ${{ matrix.plan.ghc }}
          refreshenv
          echo "::add-path::C:/Users/runneradmin/AppData/Roaming/cabal/bin"
          echo "::add-path::C:/ProgramData/chocolatey/lib/ghc/tools/ghc-${{ matrix.plan.ghc }}/bin"

      - name: Show version and paths
        shell: bash
        run: |
          ghc --version
          cabal --version

      - name: Update cabal package list
        shell: bash
        run: cabal v2-update

      - name: Write cabal.project.local with v2-configure
        shell: bash
        run: cabal v2-configure --disable-optimization

      - name: Build dependency packages
        shell: bash
        run: cabal v2-build all -j --only-dependencies

      - name: Build packages
        shell: bash
        run: cabal v2-build all

      - name: Run tests
        shell: bash
        run: cabal v2-test all

      - name: Run haddock
        shell: bash
        run: cabal v2-haddock all
