name: ci

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  pre-job:
    uses: ./.github/workflows/pre-job.yml

  stack:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.run == 'true' }}
    uses: ./.github/workflows/stack.yml
    secrets: inherit
    with:
      cache-version: v16

  cabal-install:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.run == 'true' }}
    uses: ./.github/workflows/cabal-install.yml
    with:
      cache-version: v16

  nix-build:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.run == 'true' }}
    uses: ./.github/workflows/nix-build.yml
    secrets: inherit

  make-sdist-with-stack:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.run == 'true' }}
    uses: ./.github/workflows/sdist.yml
