name: pre-job

on:
  workflow_call:
    outputs:
      run:
        description: \"true\" if running other jobs
        value: ${{ jobs.pre-job.outputs.run }}

jobs:
  pre-job:
    name: Decide whether to run other jobs
    runs-on: ubuntu-latest
    outputs:
      run: >-
        ${{
        steps.skip-check.outputs.should_skip != 'true' ||
        github.ref_name == github.event.repository.default_branch
        }}
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer
